method: bayes
metric:
  goal: maximize
  name: hypervolume
parameters:
  learning_rate:
    distribution: uniform
    min: 1e-4
    max: 1e-3
  initial_epsilon:
    distribution: uniform
    min: 0.5
    max: 1
  final_epsilon:
    distribution: uniform
    min: 0.01
    max: 0.2
  epsilon_decay_steps:
    distribution: uniform
    min: 10000
    max: 100000
  max_grad_norm:
    value: 0.1
  gamma:
    value: 0.98
  batch_size:
    value: 64
  net_arch:
    value: [256, 256, 256, 256]
  buffer_size:
    value: 2000000
  initial_homotopy_lambda:
    value: 0.0
  final_homotopy_lambda:
    value: 0.0
  homotopy_decay_steps:
    value: 10000
  learning_starts:
    value: 100
  envelope:
    value: True
  gradient_updates:
    value: 1
  target_net_update_freq:
    value: 1000
  tau:
    value: 1

# program: hyperparameter_search.py
