wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    code_path: code/examples/pgmorl_halfcheetah.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1659013144
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 35
      4: 3.9.13
      5: 0.12.21
      8:
      - 5
anneal_lr:
  desc: null
  value: false
batch_size:
  desc: null
  value: 8192
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.0
env_id:
  desc: null
  value: mo-halfcheetah-v4
evolutionary_iterations:
  desc: null
  value: 1
gae:
  desc: null
  value: true
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.995
learning_rate:
  desc: null
  value: 0.0003
limit_env_steps:
  desc: null
  value: 100000
max_grad_norm:
  desc: null
  value: 0.5
minibatch_size:
  desc: null
  value: 256
net_arch:
  desc: null
  value:
  - 64
  - 64
norm_adv:
  desc: null
  value: true
num_envs:
  desc: null
  value: 4
num_weight_candidates:
  desc: null
  value: 7
pop_size:
  desc: null
  value: 1
seed:
  desc: null
  value: 0
steps_per_iteration:
  desc: null
  value: 2048
target_kl:
  desc: null
  value: null
update_epochs:
  desc: null
  value: 10
vf_coef:
  desc: null
  value: 0.5
warm_iterations:
  desc: null
  value: 1
